AnonimForum/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.urls import re_path
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin', admin.site.urls),
    path("", include("Forum.urls")),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Forum/urls.py
from django.contrib import admin
from django.urls import path, re_path
from .views import *

urlpatterns = [
    path("", main),
    path("updates", updates),
    path("boards", boards),
    path("boards/create", boardcreation),
    path("boards/<str:board_uuid>", boardbyuuid),
    path("boards/info/<int:board_id>", boardinfo)

]

Forum/models.py
import datetime

import uuid
from django.db import models

# Create your models here.
class Update(models.Model):
    text = models.CharField(max_length=120)
    date = models.DateField(default=datetime.date.today)

class Board(models.Model):
    uuid = models.CharField(default=uuid.uuid4, blank=False, unique=True, editable=False, max_length=120)
    name = models.CharField(max_length=120)
    creation_date = models.DateField(default=datetime.date.today)
    image = models.ImageField(blank=True, upload_to="Forum/")

class Message(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    uuid = models.CharField(default=uuid.uuid4, blank=False, unique=True, editable=False, max_length=120)
    datetime = models.DateTimeField(default=datetime.datetime.now)
    text = models.TextField()

Forum/forms.py
from django import forms
from .models import Board

class MessageForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea)

class BoardCreationForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ["name", "image"]

Forum/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from .forms import *
# Create your views here.
def main(request):
    updates = Update.objects.all().order_by("-date")[:3]
    return render(request, "main.html", context={"updates": updates})

def updates(request):
    updates = Update.objects.all().order_by("-date")
    return render(request, "updates.html", context={"updates": updates})

def boards(request):
    boards = Board.objects.all().order_by("-creation_date")
    return render(request, "boards.html", context={"boards": boards})

def boardbyuuid(request, board_uuid):
    global board, messages
    if request.method == "POST":
        form = MessageForm(request.POST)
        if form.is_valid():
            Message.objects.create(board=get_object_or_404(Board, uuid=board_uuid), text=form.cleaned_data["text"]).save()
            return HttpResponseRedirect(f"/boards/{board_uuid}")
        else:
            return HttpResponse(form.errors)
    else:
        form = MessageForm()
        board = Board.objects.get(uuid=board_uuid)
        messages = Message.objects.filter(board_id=board.id)
    return render(request, "board.html", context={"form": form, "board": board, "messages": messages})


def boardcreation(request):
    if request.method == "POST":
        form = BoardCreationForm(request.POST, request.FILES)
        if form.is_valid():
            Board.objects.create(
                name=form.cleaned_data["name"],
                image=form.cleaned_data["image"]
            ).save()
            return redirect("/boards")
    else:
        form = BoardCreationForm()
        return render(request, "boardcreation.html", context={"form": form})

def boardinfo(request, board_id):
    board = get_object_or_404(Board, id=board_id)
    messages = Message.objects.filter(board_id=board.id).count()
    return render(request, "boardinfo.html", context={"board": board, "messages": messages})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block style %}{% endblock %}
</head>
<body>
<nav>
    <a href="/">Главная</a>
    <a href="/boards">Доски</a>
</nav>
<hr>

{% block body %}{% endblock %}
</body>
</html>

templates/board.html
{% extends "base.html" %}
{% load static %}
{% block style %}<link rel="stylesheet" href="{% static 'Forum/css/main.css' %}">{% endblock %}

{% block title %}Доска {{ board.name }}{% endblock %}

{% block body %}
    <img id="boardimage" src="{{ board.image.url }}">
    <a id="boardname" href="/boards/info/{{ board.id }}">{{ board.name }}</a>
    <hr class="styled-hr">
    {% for m in messages %}
        <div class="contextmenu-target-element message">
        <p class="message-text">{{ m.text }} <p class="message-datetime">{{ m.datetime }}</p></p>
        
        </div>

        {% empty %}
        <div class="contextmenu-target-element message">
        <p>Здесь пока что ничего нет?</p>
        <p class="message-datetime">256 августа 2077г. 11:11</p>
        </div>
    {% endfor %}
<hr class="styled-hr">
    <form method="post">
    {% csrf_token %}
    <textarea placeholder="Ваше сообщение" name="text" cols="40" rows="3" required="" id="id_text"></textarea>
    <input id="submit_btn" type="submit" value="отправить">
    </form>


    <div id="context-menu">
    <ul>
        <li onclick="MainFunction(`Первый пункт`)">Копировать текст</li>
        <li onclick="MainFunction(`Второй пункт`)">Цитировать</li>
        <li onclick="alert('Третий пункт')">Третий пункт</li>
    </ul>
</div>
<script src="{% static 'Forum/js/contextmenu.js' %}" ></script>
{% endblock %}

templates/boardcreation.html
{% extends "base.html" %}
{% load static %}
{% block title %}Создание доски{% endblock %}
{% block style %}
    <link rel="stylesheet" href="{% static 'Forum/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'Forum/css/createboard.css' %}">
{% endblock %}

{% block body %}
    <h1>Создание новой доски</h1>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input id="submit_btn" type="submit" value="send">
    </form>
{% endblock %}

templates/boardinfo.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Информация о доске{% endblock %}
{% block style %}<link rel="stylesheet" href="{% static 'Forum/css/main.css' %}">{% endblock %}

{% block body %}
    <img id="boardimage" width="150" height="150" src="{{ board.image.url }}">
    <h1>{{ board.name }}</h1>
    <h2>Дата создания: {{ board.creation_date }}</h2>
    <h3>Количество сообщений: {{ messages }}</h3>
{% endblock %}

templates/boards.html
{% extends "base.html" %}
{% load static %}
{% block style %}<link rel="stylesheet" href="{% static 'Forum/css/main.css' %}">{% endblock %}

{% block title %}Доски{% endblock %}

{% block body %}
    <form>
    <input type="text">
    <input type="submit" value="send">
    </form>
    <a href="/boards/create">Добавить доску</a>
    <hr>
    <div class="boards">
    {% for b in boards %}
        <div class="board">
        <img width="150" height="150" src="{{b.image.url}}">
            <a style="margin-left: 20px " href="/boards/{{ b.uuid }}">{{ b.name }}</a>
        </div>
        <hr>
    {% endfor %}
    </div>
    
{% endblock %}

templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Главная</title>
    <link rel="stylesheet" href="{% static "Forum/css/main.css" %}">
    <link rel="icon" href="{{ MEDIA_URL }}Forum/icons/pcicon.svg">
</head>
<body>
<nav>
    <a href="/">Главная</a>
    <a href="/boards">Доски</a>
</nav>
<hr>

<h1>Добро пожаловать!</h1>
<h2>Что нового?</h2>
<div>
{% for u in updates %}
    <p>{{ u.date }} - {{ u.text }}</p>
{% endfor %}
<a href="/updates">Все обновления</a>
</div>

</body>
</html>

templates/updates.html
{% extends "base.html" %}
{% load static %}
{% block title %}Все обновления{% endblock %}
{% block style %} <link rel="stylesheet" href="{% static 'Forum/css/main.css' %}"> {% endblock %}
{% block body %}
    {% for u in updates %}
        <p>{{ u.date }} - {{ u.text }}</p>
    {% endfor %}
{% endblock %}